

function feature = sssFeature

feature = struct('name', '', ...
                 'xyz', [],  ...
                 'radius', [], ... 
                 'cov', [], ...
                 'times', datetime, ... 
                 'error', [], ...
                 'matchXY', [], ...
                 'matchName', '', ...   
                 'matchTime', [], ...
                 'matchImage', [], ...
                 'image', [], ...
                 'vehicle',[], ...
                 'vehicle_cov', [], ...
                 'ind', []);
end